image: node:latest

eslint:
  stage: test
  script:
    - cd backend
    - npm install
    - npm run lint

jest:
  stage: test
  script:
    - cd backend
    - npm install
    - npm test
  coverage: '/^All files\s+\|\s+\d+\.*\d*\s+\|\s*(\d+\.*\d*)/'
  artifacts:
    paths:
      - backend/coverage/

pages:
  stage: deploy
  script:
    - mv backend/coverage/lcov-report/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master
