image: node:latest

stages:
  - test

eslint:
  stage: test
  script:
    - cd backend
    - npm install
    - npm run lint

jest:
  stage: test
  script:
    - cd backend
    - npm install
    - npm test
  coverage: '/^All files\s+\|\s+\d+\.*\d*\s+\|\s*(\d+\.*\d*)/'
