image: node:latest

stages:
  - first
  - second

eslint:
  stage: first
  script:
    - cd backend
    - npm install
    - npm run lint

jest:
  stage: first
  script:
    - cd backend
    - npm install
    - npm test
  coverage: '/^All files\s+\|\s+\d+\.*\d*\s+\|\s*(\d+\.*\d*)/'
  artifacts:
    paths:
      - backend/coverage/
    expire_in: 30 days

pages:
  image: alpine
  stage: second
  script:
    - apk add curl
    - cd backend/coverage
    - tar cf lcov-report.tar lcov-report
    - curl https://mcc.zi.fi/mccproject -X POST -T lcov-report.tar
  only:
    - master

frontend:
  image: mreichelt/android:29
  stage: second
  script:
    - cd frontend/TaskApplication/
    - ./gradlew check assemble
    - mv app/build/outputs/apk/*/*.apk ../../
  artifacts:
    paths:
      - "*.apk"
