swagger: "2.0"
info:
  title: "Task management api"
  version: "0.0.1"
schemes:
  - "https"
host: "mcc-fall-2019-g09.appspot.com"
basePath: "/"
consumes:
  - application/json
produces:
  - application/json

definitions:
  member:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int32"
  members:
    type: "array"
    minItems: "1" # "(it can contain one or more users)" ???
    items:
      $ref: '#/definitions/member'
  taskAttributes:
    type: "object"
    properties:
      description:
        type: "string"
      status:
        $ref: '#/definitions/taskStatus'
      #deadline:
      #  type: ""
  taskStatus:
    type: "string"
    enum: ["pending", "on-going", "completed"]

paths:
  /project:
    post:
      operationId: "createProject"
      description: "Create a project"
      responses:
        200:
          description: "Project id"
          schema:
            type: "integer"
            format: "int32"
  #/project/{projectId}:
  #  delete:
  #    operationId: "deleteProject"
  #    description: "Delete a project"
  #/project/{projectId}/members:
  #  post:
  #    operationId: "addProjectMembers"
  #    description: "Add members to a project"
  #/project/{projectId}/task:
  #  post:
  #    operationId: "createProjectTask"
  #    description: "Create a task"
  #/project/{projectId}/task/{taskId}/:
  #/task:
  #  post:
  #    operationId: "createTask"
  #    description: "Create a task"
