FROM google/cloud-sdk:272.0.0
RUN curl -sL https://deb.nodesource.com/setup_13.x | bash - && \
apt-get install -y nodejs
RUN npm install -g firebase-tools
ENV FIREBASE_TOKEN 1//0cJrTCiG9VgweCgYIARAAGAwSNwF-L9IrqmqKlAPHkfHcDExc4qGnXhdFxLX8NRhnpgrEQ0ZPBTipR0cDO9qSTvXoCN6a3HU5GJE
